version: '3.8'

services:
  # API service (Spring Boot)
  api:
    build: ./app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/clase3"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "1234"

  # MySQL database
  db:
    image: mysql:8
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "clase3"
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_USER: "root"
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

volumes:
  db_data: