services:
 # API service
 # This service runs a Spring Boot application that connects to a MySQL database
 api:
 build: ./app
 ports:
 - "8080:8080"
 #espera a que el serivicio de base de datos este disponible
 # y luego ejecuta el servicio de la API
 depends_on:
 - db
 environment:
 - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/clase3
 - SPRING_DATASOURCE_USERNAME=root
 - SPRING_DATASOURCE_PASSWORD=1234

# Mysql service
 db:
 # This service runs a MySQL database
 # It uses the official MySQL image from Docker Hub
 image: mysql:8
 volumes:
 - db_data:/var/lib/mysql
 # The environment variables set the database name and root password for MySQL
 # The root password is set to '1234' for this example
 restart: always
 # The ports section maps the MySQL port inside the container to the host machine 
 his allows you to connect to the MySQL database from your host machine
 environment:
 MYSQL_DATABASE: clase3
 MYSQL_ROOT_PASSWORD: 1234
 Mysql_USER: root

 # The ports section maps the MySQL port inside the container to the host machine
 # This allows you to connect to the MySQL database from your host machine
 ports:
 - "3306:3306"
volumes:
 db_data: